# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'cucumber'
gem 'httparty'
gem 'json'
gem 'report_builder'
gem 'rspec'
gem 'rubocop'
